"""Make recipe_id nullable for import table

Revision ID: 0b3cf91a02f3
Revises: 5cdf45533a22
Create Date: 2026-02-04 12:38:15.687561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b3cf91a02f3'
down_revision: Union[str, Sequence[str], None] = '5cdf45533a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('imports', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('imports', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
