"""Link import to user

Revision ID: 0be2bfab7c1b
Revises: f6846779716a
Create Date: 2026-02-09 21:58:57.928624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be2bfab7c1b'
down_revision: Union[str, Sequence[str], None] = 'f6846779716a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imports', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'imports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'imports', type_='foreignkey')
    op.drop_column('imports', 'user_id')
    # ### end Alembic commands ###
