"""Remove source_file from import table

Revision ID: 3f28e3dfae02
Revises: 0b3cf91a02f3
Create Date: 2026-02-04 19:01:59.634344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f28e3dfae02'
down_revision: Union[str, Sequence[str], None] = '0b3cf91a02f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imports', 'source_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imports', sa.Column('source_file', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
