"""add recipe id to import

Revision ID: 9b71636233de
Revises: 07083bb09393
Create Date: 2026-02-03 17:57:36.443030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b71636233de'
down_revision: Union[str, Sequence[str], None] = '07083bb09393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imports', sa.Column('recipe_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'imports', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'imports', type_='foreignkey')
    op.drop_column('imports', 'recipe_id')
    # ### end Alembic commands ###
