"""Add membership plan

Revision ID: c9ad2a0f162c
Revises: 0be2bfab7c1b
Create Date: 2026-02-10 22:12:57.583030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ad2a0f162c'
down_revision: Union[str, Sequence[str], None] = '0be2bfab7c1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan', sa.String(), nullable=False, server_default="free"))
    op.add_column('users', sa.Column('recipe_count', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recipe_count')
    op.drop_column('users', 'plan')
    # ### end Alembic commands ###
