"""Link recipe to user

Revision ID: f6846779716a
Revises: 70a22c4ef7df
Create Date: 2026-02-09 21:37:27.088231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6846779716a'
down_revision: Union[str, Sequence[str], None] = '70a22c4ef7df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'recipes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'user_id')
    # ### end Alembic commands ###
